package mx.gob.imss.mssintrans.ccom.traslados.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import mx.gob.imss.mssintrans.ccom.traslados.model.SiniestroDetalleEntity;

public interface SiniestroDetalleRepository extends JpaRepository<SiniestroDetalleEntity, Integer> {
	@Query(value = ""
			+ "SELECT  	SS.*,SV.CVE_ECCO,SV.ID_VEHICULO,SV.CVE_ECCO,SV.NUM_PLACAS,SV.DES_ESTATUS_VEHICULO, SRA.ID_REASIGNACION,SA.NOM_ARRENDADORA, SAS.DES_NOMBRE_ASEGURADORA, SC.NOM_CHOFER   "
			+ "FROM    	SINTRANST_SINIESTROS SS															 "
			+ "INNER		JOIN 	SINTRANST_VEHICULOS SV ON SV.ID_VEHICULO = SS.ID_VEHICULO	 "
			+ "LEFT OUTER		JOIN SINTRANST_ARRENDATARIOS SA ON SA.ID_ARRENDATARIO = SV.ID_ARRENDATARIO		 "
			+ "LEFT OUTER		JOIN SINTRANSC_ASEGURADORAS SAS ON SAS.ID_ASEGURADORA = SV.ID_ASEGURADORA	 	 "
			+ "INNER		JOIN SINTRANST_REASIGNACION_RUTAS SRA ON SRA.ID_REASIGNACION = SS.ID_REASIGNACION    "
			+ "INNER		JOIN SINTRANST_CHOFERES SC ON SC.ID_CHOFER = SRA.ID_CHOFER	 "
			+ "WHERE 		SS.IND_ACTIVO 	= '1'	AND	SS.ID_SINIESTRO=? "
	// + "AND SV.IND_ARRENDADO = 1 "
			, countQuery = " SELECT COUNT(SS.ID_SINIESTRO)                     "
					+ "FROM    	SINTRANST_SINIESTROS SS															 "
					+ "INNER		JOIN 	SINTRANST_VEHICULOS SV ON SV.ID_VEHICULO = SS.ID_VEHICULO	 "
					+ "LEFT OUTER		JOIN SINTRANST_ARRENDATARIOS SA ON SA.ID_ARRENDATARIO = SV.ID_ARRENDATARIO		 "
					+ "LEFT OUTER		JOIN SINTRANSC_ASEGURADORAS SAS ON SAS.ID_ASEGURADORA = SV.ID_ASEGURADORA	 	 "
					+ "INNER		JOIN SINTRANST_REASIGNACION_RUTAS SRA ON SRA.ID_REASIGNACION = SS.ID_REASIGNACION    "
					+ "INNER		JOIN SINTRANST_CHOFERES SC ON SC.ID_CHOFER = SRA.ID_CHOFER	 "
					+ "WHERE 		SS.IND_ACTIVO 	= '1'	AND	SS.ID_SINIESTRO=? "
					, nativeQuery = true)
	SiniestroDetalleEntity obtenerConsultaPorId(Integer id);

}
