server:
  port: 8098
  servlet:
    contextPath: /mssintrans-ccom-traslados
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SITCDQA
    username: pmsoluciones
    password: Tr1357.*
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      maximum-pool-size: 1
      
  main:
    allow-circular-references: true
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error
    mx.gob.imss.mssintetrans.vehiculos: error

logos:
  logo-imss: ${msit_LOGO_IMSS}
  logo-sistema: ${msit_LOGO_SISTEMA}
endpoints:
  carga-archivos-endpoint: ${msit_SINTRANS_CARGA}
  siap-endpoint: ${msit_SINTRANS_SIAP}
  
archivos:
  agrupador-siniestro: "SINIESTRO"

jwt:
  secretkey: ${msit_SECRET_KEY}
    
